# Top 20 for every month
```{r}
library(data.table)
library(stringr)

library(dplyr)
library(openxlsx)
library(readxl)
library(ggplot2)

df <- fread("/home/justinz/Malay_Drug_Disease/all_merged_df.txt", sep = ";")
df$drug <- gsub("\\s*\\d+(/\\d+)?\\s*mg", "", df$DRUG_NAME)
df$drug <- gsub(" \\(.*)", "", df$drug)



output_dir <- "/home/justinz/Malay_Drug_Disease/time_series/"


f_df <- df[df$DRUG_NAME != "DUPLICATED" & df$ICD_CODE != "DUPLICATED", ]
f_df$month <- month.abb[as.numeric(f_df$month)]
# Top 20 ICD codes by month
top_icd <- f_df %>%
        group_by(month, ICD_CODE) %>%
        summarise(n = n()) %>%
        arrange(desc(n)) %>%
        mutate(rank = row_number()) %>%
        slice_max(order_by = n, n = 20) %>%
        arrange(month, desc(n))
top_icd$month <- factor(top_icd$month, levels = month.abb[1:11])
top_icd <- top_icd[order(top_icd$month), ]

# Create the ggplot bar plot
p <- ggplot(top_icd, aes(x=reorder(ICD_CODE, -n), y=n, fill=ICD_CODE)) +
            geom_bar(stat="identity") +
            facet_wrap(~month, scales="free_x") +
            scale_y_continuous(trans = "log10") +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 90, hjust = 1),
                plot.title = element_text(hjust = 0.5)) +
            labs(x="ICD Code", y="Count", fill="ICD Code", title = "Top 20 diseases (log10) ~ Month")

p_title <- paste0(output_dir, "topN_ICD_allmonths.png")
ggsave(filename = p_title,
    plot = p, width = 14, height = 6, units = "in")

# Convert 'month' to a factor with levels ordered
top_icd$month <- factor(top_icd$month, levels = month.abb[1:11], ordered = TRUE)
p <- ggplot(top_icd[top_icd$ICD_CODE != "BA00.Z", ], aes(x=month, y=n, group=ICD_CODE, color=ICD_CODE)) +
    geom_line() +
    theme_bw() +
    theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        # legend.position = "none",
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 20)) +
    labs(x="Month", y="Count", color="ICD_CODE", title = "Monthly changes of every disease")

p_title <- paste0(output_dir, "ICD_monthly_changes.png")
ggsave(filename = p_title,
    plot = p, width = 8, height = 4, units = "in")

```

# Drug without Dosages
```{R}
# Top 20 drugs by month
top_drug <- f_df %>%
        group_by(month, drug) %>%
        summarise(n = n()) %>%
        arrange(desc(n)) %>%
        mutate(rank = row_number()) %>%
        slice_max(order_by = n, n = 20) %>%
        arrange(month, desc(n))
top_drug$month <- factor(top_drug$month, levels = month.abb[1:11])
top_drug <- top_drug[order(top_drug$month), ]

    # Create the ggplot bar plot
p <- ggplot(top_drug, aes(x=reorder(drug, -n), y=n, fill=drug)) +
            geom_bar(stat="identity") +
            facet_wrap(~month, scales="free_x") +
            scale_y_continuous(trans = "log2") +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 90, hjust = 1),
                plot.title = element_text(hjust = 0.5)) +
            labs(x="Drug", y="Count", fill="Drug", title = "Top 20 drugs (log2) ~ Month")

p_title <- paste0(output_dir, "topN_Drug_allmonths.png")
ggsave(filename = p_title,
    plot = p, width = 14, height = 6, units = "in")


# Convert 'month' to a factor with levels ordered
top_drug$month <- factor(top_drug$month, levels = month.abb[1:11], ordered = TRUE)

p <- ggplot(top_drug, aes(x=month, y=n, group=drug, color=drug)) +
    geom_line() +
    theme_bw() +
    theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        # legend.position = "none",
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 20)) +
    labs(x="Month", y="Count", color="drug", title = "Monthly changes of each drug")

p_title <- paste0(output_dir, "Drug_monthly_changes.png")
ggsave(filename = p_title,
    plot = p, width = 16, height = 8, units = "in")

# No Amlodipine
p <- ggplot(top_drug[top_drug$drug != "Amlodipine", ], aes(x=month, y=n, group=drug, color=drug)) +
    geom_line() +
    theme_bw() +
    theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        # legend.position = "none",
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 20)) +
    labs(x="Month", y="Count", color="drug", title = "Monthly changes of each drug")

p_title <- paste0(output_dir, "Drug_monthly_changes_No_Amlodipine.png")
ggsave(filename = p_title,
    plot = p, width = 16, height = 8, units = "in")
```

# Now let's take in account of the dosage information
```{r}
f_df$drug_dosage <- gsub(" \\(.*)", "", f_df$DRUG_NAME)

f_df[f_df$drug_dosage == top_drugName$drug_dosage[1], ]

f_df[f_df$ICD_CODE == "BA00.Z", ]

# Top 20 drug dosages by month
top_drugName <- f_df %>%
        group_by(month, drug_dosage) %>%
        summarise(n = n()) %>%
        arrange(desc(n)) %>%
        mutate(rank = row_number()) %>%
        slice_max(order_by = n, n = 20) %>%
        arrange(month, desc(n))
top_drugName$month <- factor(top_drugName$month, levels = month.abb[1:11])
top_drugName <- top_drugName[order(top_drugName$month), ]


# Create the ggplot bar plot
p <- ggplot(top_drugName, aes(x=reorder(drug_dosage, -n), y=n, fill=drug_dosage)) +
            geom_bar(stat="identity") +
            coord_flip() +
            facet_wrap(~month, scales="free_x") +
            # scale_y_continuous(trans = "log2") +
            theme_bw() +
            theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1),
                plot.title = element_text(hjust = 0.5),
                legend.position = "none",
                axis.text.y = element_text(size = 20),  # Added this line to change y-axis text size
                axis.title = element_text(size = 20)) +
            labs(x="Drug+Dosage", y="Count", fill="drug_dosage")

p_title <- paste0(output_dir, "topN_DrugDosage_allmonths.png")
ggsave(filename = p_title,
    plot = p, width = 20, height = 20, units = "in")


# Convert 'month' to a factor with levels ordered
top_drugName$month <- factor(top_drugName$month, levels = month.abb[1:11], ordered = TRUE)

p <- ggplot(top_drugName, aes(x=month, y=n, group=drug_dosage, color=drug_dosage)) +
    geom_line() +
    theme_bw() +
    theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        # legend.position = "none",
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 20)) +
    labs(x="Month", y="Count", color="drug_dosage", title = "Monthly changes of each drug")

p_title <- paste0(output_dir, "DrugDosage_monthly_changes.png")
ggsave(filename = p_title,
    plot = p, width = 16, height = 8, units = "in")
```

# With disease, we should focus on the newly emerging ones of specific months
# With drugs, we should focus on the differecnces between every month
```{r}

```